### PR TITLE
Add Flatpak support

### LINKED ISSUE #15: Doesn't work on RetroArch Flatpak
When I try to run a GameCube game on RetroArch using libretro-dolphin-launcher, it shows the following message:

sh: dolphin-emu-nogui: command not found
sh: dolphin-emu: command not found
...
dolphin-emu-nogui not found, trying dolphin-emu

The command "dolphin-emu" works on my machine. I believe it is somehow related to Flatpak (I installed RetroArch flatpak).

I know that by now we have an official Dolphin libretro implementation, but it's still in Alpha stage and, on my machine, is too slow. Dolphin Emulator standalone works perfect.

If I can provide some more help to troubleshooting the problem, I'm here for it.

### PR DESCRIPTION
**Pull request by RobLoach**
@coldscientist Mind testing this???

I've found the lack of `-nogui` is kind of unfortunate. Made an issue in the Flathub queue about that.

Fixes #15

### CODE REVIEW

**Comment by eduardomozart** [comment]
I'm on it.

Find some interesting links. 

https://github.com/flatpak/flatpak/wiki/Filesystem
http://docs.flatpak.org/en/latest/working-with-the-sandbox.html

Flatpak uses some kind of Sandbox for it apps and, aparently, it cannot access other apps (even Flatpak apps) by default. I tried to override Flatpak permissions, but no lucky so far, but I'll keep trying!

**Comment by RobLoach** [comment]
I was able to run the Flatpak install of Dolphin through a natively installed RetroArch. I'll try all flatpak.

**Comment by RobLoach** [comment]
```
sh: -e: command not found
sh: --batch: command not found
sh: --batch: command not found
dolphin-emu-nogui not found, trying dolphin-emudolphin-emu failed. Trying Flatpak.Failed running Dolphin. Install it and try again.
```

**Comment by eduardomozart** [comment]
I'm happy that it's working outside Flatpak. It is a possibility that I may try if nothing works at all. I would like to avoid installing retroarch from the repo of my dist because it is modified in a way that it disallow core installations (I can only use the ones provided by libretro* packages through apt-get). I didn't want to have to install cores manually. But I can do it if nothing works.

I'm doing some tests, replacing "dolphin-emu" with the 'ls' command and executing Flatpak with the command:

flatpak run --filesystem=host org.libretro.RetroArch/x86_64/stable -v

It can access my filesystem but when I try to 'ls' /usr/game (where Dolphin is installed) it doesn't show any executable (even it existing on my host OS). 'ls' /usr return the same result. 

By now, I discovered with the command 'which retroarch > /home/eduardo/test.txt' inside system(command), that retroarch is located at '/app/bin/retroarch' inside sandbox.

Inside my OS, '/app' is located at ~/.local/share/flatpak/app/org.libretro.RetroArch/current/active/files

**Comment by eduardomozart** [comment]
When I copy /usr/games/dolphin-emu to ~/.local/share/flatpak/app/org.libretro.RetroArch/current/active/files/bin, it finds dolphin-emu and shows the following message:

sh: dolphin-emu-nogui: command not found
/app/bin/dolphin-emu: error while loading shared libraries: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Now it finds dolphin-emu. It's a dirty hack, I know, but just to comprove a possibility.

Somehow Flatpak hides executable binaries from the RetroArch Flatpak app (probably a security measure). When I created a link from /usr/games/dolphin-emu to the RetroArch 'files' folder, it is hidden from the app. But when I copy it to the 'files/bin' folder, I can access it through Sandbox.

I'm trying to find a way to Flatpak apps see each other, so we could call Dolphin Flatpak from there...

**Comment by eduardomozart** [comment]
I could not find an effective solution for this problem.

I used 'find' into system(command) and it hides most libraries and binaries from the system. Only when I copy the 'dolphin-emu' binary it is available from RetroArch Flatpak.

I don't think that exist some non-dirty way to do it. Even giving Flatpak access to all files from the filesystem with --filesystem=host it didn't show up others Flatpak applications or libraries (that Dolphin needs to be executed).

I'll give up and install RetroArch from PPA. Maybe someday we found a solution for this.

Thanks for the attention Rob Loach! I'll give you feedback after RetroArch PPA install and libretro-dolphin-launcher.

**Comment by RobLoach** [comment]
I'll merge this one in the mean time. Seems handy to be able to run from native to Flatpak dolphin.

**Pull request merged**
